#Файл конфигурации
POSTGRES_DB: "postgres"
POSTGRES_USER: "postgres"
POSTGRES_PASSWORD: 1234
DATABASE_URL: postgres://postgres:1234@localhost:5432/taskflow
REDIS_URL: redis://redis:6379/0
WORKER_COUNT: 5
RATE_LIMIT: 20
LOG_LEVEL: "Info"
LOG_FORMAT: "Json"